### ISSUE TITLE
the resoult  is not good by combining llama2 and sd

### ISSUE THREAD

**Issue by xiaoyingzhengrui** [ShihaoZhaoZSH/LaVi-Bridge#5]
thanks for sharing this good project. i want to generate the picture by using language model.
i download the llama2-7b and the adapter as provided, but the resoult i got is not as good as the paper shows.  so i want to know what's the precision about llama2-7b and sd-v1.4 models. i can see the code that is using llama2-7b in fp16, but not sure for the vae and u-net , 
 i tested in fp32 and fp16, the picture style and detail is pretty strange.

**Comment by ShihaoZhaoZSH** [comment]
You can perform inference according to the settings provided in the script. Considering that our training data includes both low-quality COCO data and high-quality internal data, we recommend using descriptive words in prompts to enhance the quality of generated images, as this aligns better with the distribution of our high-quality internal dataset. You can refer to the prompts in the paper for further guidance. You can also refer to the Section D in the appendix of our research paper.

**Comment by ShihaoZhaoZSH** [comment]
Thank you for your interest in our LaVi-Bridge! In our experiments, we utilize fp16 for obtaining the text embedding and subsequently convert it to fp32 for image generation, following the same way as shown in the script. We have made some updates, so please update the repository and give it another try.
