### ISSUE TITLE
LLAMA2 version

### ISSUE THREAD

**Issue by tanshuai0219** [ShihaoZhaoZSH/LaVi-Bridge#9]
which llama2 version can match your released lora weights？ Could you share the huggingface link of the correct llama2 version?

Can the version "https://huggingface.co/NousResearch/Llama-2-7b-hf" work well with your released lora weights?

Thanks for your reply~

**Comment by ShihaoZhaoZSH** [comment]
Here is the link: https://huggingface.co/meta-llama/Llama-2-7b-hf

**Comment by tanshuai0219** [comment]
> Here is the link: https://huggingface.co/meta-llama/Llama-2-7b-hf

Thanks for your quick reply~ The issue will be closed.

**Comment by dawei03896** [comment]
Does it support 8bit or 4bit LLAMA2?
